### ISSUE TITLE
Timeouts - decaying, fixed or continuous

### ISSUE THREAD

**Issue by espenjutte** [Stefan-Code/peer-harvest#8]
(copy/paste from the PEX-issue)
Since we are now getting PEX we end up with a timeout problem: when do we stop? We currently have a timeout running, What i'm thinking might be more effective would be to have a configurable X-second decaying timeout for new peers. In other words: If we don't see any new peers for 10 seconds, end the script and dump the file.

Another option would be to keep polling trackers, DHT and PEX until the script ends. This is a bit less brute-force but we would have to be mindfull of timeouts and kinda manage our connections/who to re-poll etc. This could work since PEX-connection actually send diffs, (added/removed) since last request, so one could in theory keep polling to get a overview of the network.

**Comment by espenjutte** [comment]
I like the decaying timeout myself for a early version, seems to be the most logical approach to get good results without adding to much work.

On the other hand, a continuously polling version might not be that much harder inn nodejs due to the event-based nature. We would simply have to think about what peers we keep relations too and why, because reconnecting and restarting everything for each poll is not really very efficient.

**Comment by Stefan-Code** [comment]
I suggest the following:
We keep the `--timeout` switch basically as before, but **don't assume the default of 3 minutes**. Additionally, we add a new switch called `--timeout-no-peers`.
If `--timeout` is not set, keep running until `--timeout-no-peers` sets in. The `--timeout-no-peers` timeout should have a **default** of around _20-30 sec_ (or so?) after a peer is found. Before that, something longer like _2-3 mins_ (to give establishing of DHT time). The `--timeout` **limits the total running time** no matter if new peers are coming in or not. That way the user has absolute control over how long the Program runs, but if not specified, it collects information until no new peers are found. What do you think? The continuously polling version could of course be added sometimcontinuoslye later, too.

**Comment by espenjutte** [comment]
This seems perfect, good plan.
